# Generated by Django 3.2.25 on 2025-03-17 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deliveryboy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryboyname', models.CharField(max_length=100)),
                ('license', models.CharField(max_length=100)),
                ('vehiclestatus', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ordermain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('post', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('adhar', models.CharField(default='', max_length=200)),
                ('Dob', models.DateField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('shopname', models.CharField(max_length=100)),
                ('shopdistrict', models.CharField(max_length=100)),
                ('shoppincode', models.CharField(max_length=100)),
                ('shopphone', models.CharField(max_length=100)),
                ('shopemail', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('ownername', models.CharField(max_length=100)),
                ('ownerphone', models.BigIntegerField()),
                ('owneremail', models.CharField(max_length=100)),
                ('ownerplace', models.CharField(max_length=100)),
                ('ownerpost', models.CharField(max_length=100)),
                ('ownerpincode', models.BigIntegerField()),
                ('ownerdistrict', models.CharField(max_length=100)),
                ('ownerstate', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('shoplicense', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.CharField(max_length=100)),
                ('review', models.CharField(default='', max_length=500)),
                ('USERNAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('ORDERMAIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ordermain')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ordersub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('DRESS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dress')),
                ('ORDERMAIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ordermain')),
            ],
        ),
        migrations.AddField(
            model_name='ordermain',
            name='SHOP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shop'),
        ),
        migrations.AddField(
            model_name='ordermain',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.CreateModel(
            name='Orderassign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('DELIVERYBOY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.deliveryboy')),
                ('ORDERMAIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ordermain')),
            ],
        ),
        migrations.CreateModel(
            name='MyDress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('m1', models.CharField(max_length=100)),
                ('m2', models.CharField(max_length=100)),
                ('m3', models.CharField(max_length=100)),
                ('m4', models.CharField(max_length=100)),
                ('m5', models.CharField(max_length=100)),
                ('m6', models.CharField(max_length=100)),
                ('m7', models.CharField(max_length=100)),
                ('m8', models.CharField(max_length=100)),
                ('m9', models.CharField(max_length=100)),
                ('m10', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='dress',
            name='SHOP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shop'),
        ),
        migrations.AddField(
            model_name='dress',
            name='TONES',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tones'),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=100)),
                ('DRESS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dress')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Assigntailor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('ORDERMAIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ordermain')),
                ('TAILOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tailor')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
