# Generated by Django 3.2.25 on 2025-03-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
    ]
