# Generated by Django 3.0 on 2025-11-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dress_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='LOGIN',
        ),
        migrations.RemoveField(
            model_name='orderassign',
            name='DELIVERYBOY',
        ),
        migrations.RemoveField(
            model_name='orderassign',
            name='ORDERMAIN',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='dress',
            name='SHOP',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Assigntailor',
        ),
        migrations.DeleteModel(
            name='Deliveryboy',
        ),
        migrations.DeleteModel(
            name='Orderassign',
        ),
    ]
