# Generated by Django 3.0 on 2025-11-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dob',
            new_name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
