# Generated by Django 3.0 on 2025-11-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20251122_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermain',
            name='SHOP',
        ),
    ]
