# Generated by Django 3.0 on 2025-12-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_ordermain_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='LOGIN',
        ),
        migrations.RemoveField(
            model_name='orderassign',
            name='DELIVERYBOY',
        ),
        migrations.RemoveField(
            model_name='orderassign',
            name='ORDERMAIN',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='LOGIN',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='LOGIN',
        ),
        migrations.DeleteModel(
            name='Assigntailor',
        ),
        migrations.DeleteModel(
            name='Deliveryboy',
        ),
        migrations.DeleteModel(
            name='Orderassign',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.DeleteModel(
            name='Tailor',
        ),
    ]
