# Generated by Django 3.0 on 2026-01-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20251216_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='USERNAME',
        ),
        migrations.AddField(
            model_name='reviews',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
            preserve_default=False,
        ),
    ]
