# Generated by Django 3.0 on 2026-01-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20260117_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='USER',
            new_name='USERNAME',
        ),
    ]
