# Generated by Django 3.0 on 2026-01-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20260117_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='USERNAME',
            new_name='USER',
        ),
    ]
